# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

gem 'rake'
gem 'activesupport', require: false
gem 'safe_attribute_assignment'
gem 'danica'
gem 'recursive-open-struct'
gem 'darthjee-core_ext', '~> 1.5.3'
